# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Quiénes Somos
    weight: 10
    identifier: "quienes-somos"
  - name: Historia
    url: '/historia'
    weight: 20
    parent: "quienes-somos"
  - name: Patrimonio
    url: '/patrimonio'
    weight: 30
    parent: "quienes-somos"
  - name: Repertorio
    url: '/repertorio'
    weight: 40
    parent: "quienes-somos"
  - name: Discografía
    url: '/discografia'
    weight: 50
    parent: "quienes-somos"
  - name: Actuaciones
    url: '/actuaciones'
    weight: 60
  - name: Vídeos
    url: '/videos'
    weight: 70
  - name: Blog
    url: '/post'
    weight: 80
  - name: Multimedia
    weight: 90
    identifier: "multimedia"
  - name: Imágenes
    url: '/imagenes'
    weight: 100
    parent: "multimedia"
  - name: Contacto
    url: '/contacto'
    weight: 110

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
